version: 2.1
executors:
  default_image:
    docker:
    - image: cimg/base:current
jobs:
  snyk-pipeline:
    environment:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    executor: default_image
    steps:
    - checkout
    - run:
        name: Setup Snyk + snyk-to-html
        command: |
          npm install snyk -g
          npm install snyk-to-html -g
          snyk auth ${{secrets.SNYK_TOKEN}}
    - run:
        name: Snyk Open Source
        command: snyk monitor
    - run:
        name: Snyk Code
        command: |
          snyk code test || true
          
    - run:
        name: Snyk SCA
        command: snyk test || true
workflows:
  Synk_GHAS_Test_Scan:
    jobs:
    - snyk-pipeline:
        filters:
          branches:
            only:
            - main
          tags: {}
# Translated via CircleCI's Configuration Translator
# Info :: Could not translate "pull_request" trigger event to an equivalent in CircleCI's config.yml